Repository redeclipse/base, pull requests merged in 2020-01, with the labels that each got.

#990 generalize architecture handling a little
  redeclipse.sh
  src/CMakeLists.txt
  src/Makefile
  src/get_binarch.sh
Labels: branch: master, difficulty: medium, status: enhancement

#986 Don't display the `/0` ammo store on the HUD for grenades/rockets/mines
  config/ui/hud.cfg
Labels: branch: master, difficulty: easy, status: bug, status: enhancement

#983 Improve ping coloring in the server browser
  config/ui/servers.cfg
  src/engine/rendertext.cpp
Labels: branch: master, difficulty: easy, status: enhancement

#981 Print the modified map CRC message only when the map CRC differs
  src/game/server.cpp
Labels: branch: master, difficulty: easy, status: enhancement, status: please discuss further

#979 Don't emit player boost particles while paused
  src/game/game.cpp
Labels: branch: master, difficulty: easy, status: bug

#978 Improve the display of default/modified variables in the console
  config/ui/console.cfg
Labels: branch: master, difficulty: easy, status: enhancement

#977 Use a more visible cyan colour for entities in edit mode
  src/game/entities.cpp
Labels: branch: master, difficulty: easy, status: enhancement

#973 Automatically use integer scaling when using a `gscale` of 25 or 50
  src/engine/renderlights.cpp
Labels: branch: master, difficulty: easy, status: enhancement

#996 fix ui color out-of-bounds access
  src/engine/ui.cpp
Labels: branch: master, branch: stable, difficulty: easy, status: bug

#997 fix oldhook out-of-bounds
  src/engine/sound.cpp
Labels: branch: master, branch: stable, difficulty: easy, status: bug

#998 sound command cleanup
  src/engine/sound.cpp
Labels: branch: master, difficulty: easy, status: enhancement
