Repository redeclipse/base, pull requests merged in 2020-05, with the labels that each got.

#1042 Shadows for transparent geometry
  config/glsl/deferred.cfg
  config/glsl/smfilter.cfg
  config/glsl/world.cfg
  config/ui/settings.cfg
  config/usage.cfg
  src/engine/engine.h
  src/engine/octaedit.cpp
  src/engine/renderlights.cpp
  src/engine/renderva.cpp
  src/engine/texture.cpp
  src/engine/texture.h
  src/engine/world.h
  src/engine/worldio.cpp
  src/game/game.h
Labels: difficulty: hard, status: enhancement

#1053 move default sky/edit texture config
  config/map/default.cfg
  config/map/textures.cfg
Labels: status: bug

#1052 Request dedicated GPU when starting Red Eclipse from the `.desktop` file
  src/install/nix/redeclipse.desktop.am
Labels: branch: master, status: please discuss further

#1056 vshadow variable for alpha shadow opacity control
  config/glsl/world.cfg
  config/usage.cfg
  src/engine/octaedit.cpp
  src/engine/renderva.cpp
  src/engine/texture.cpp
  src/engine/texture.h
  src/engine/worldio.cpp
Labels: branch: master, difficulty: medium, status: enhancement
