Repository redeclipse/base, pull requests merged in 2020-09, with the labels that each got.

#937 scriptable FX
  config/defaults.cfg
  config/fx.cfg
  config/fx/lib.cfg
  config/fx/particle.cfg
  config/fx/projs/airblast.cfg
  config/fx/projs/beam.cfg
  config/fx/projs/bullet.cfg
  config/fx/projs/casing.cfg
  config/fx/projs/debris.cfg
  config/fx/projs/energy.cfg
  config/fx/projs/flak.cfg
  config/fx/projs/flame.cfg
  config/fx/projs/gib.cfg
  config/fx/projs/grenade.cfg
  config/fx/projs/mine.cfg
  config/fx/projs/pellet.cfg
  config/fx/projs/plasma.cfg
  config/fx/projs/projs.cfg
  config/fx/projs/rocket.cfg
  config/fx/projs/shrapnel.cfg
  config/fx/projs/vortex.cfg
  config/fx/sound.cfg
  config/fx/stain.cfg
  config/fx/std.cfg
  config/fx/weapons/airblast.cfg
  config/fx/weapons/beam.cfg
  config/fx/weapons/energy.cfg
  config/fx/weapons/flame.cfg
  config/fx/weapons/muzzle.cfg
  config/fx/weapons/plasma.cfg
  config/fx/weapons/weapons.cfg
  src/Makefile
  src/engine/dynlight.cpp
  src/engine/engine.h
  src/engine/fx.cpp
  src/engine/fx.h
  src/engine/fxemit.cpp
  src/engine/fxprop.cpp
  src/engine/fxprop.h
  src/engine/main.cpp
  src/engine/rendergl.cpp
  src/engine/renderparticles.cpp
  src/engine/sound.cpp
  src/engine/sound.h
  src/engine/wind.cpp
  src/engine/wind.h
  src/engine/world.cpp
  src/game/game.cpp
  src/game/game.h
  src/game/projs.cpp
  src/game/weapons.h
  src/shared/cube.h
  src/shared/geom.h
  src/shared/iengine.h
  src/shared/igame.h
  src/shared/prop.cpp
  src/shared/prop.h
  src/shared/tools.h
Labels: branch: master, difficulty: hard, status: enhancement, status: please discuss further

#1086 Update guidelines.txt
  doc/guidelines.txt
Labels: branch: master, priority: low, status: enhancement

#969 Only display moving animations when the player is actually moving
  src/game/game.cpp
Labels: branch: master, difficulty: easy, status: enhancement

#1082 fix ui commands for clearwaypoints/delselwaypoints
  config/ui/editing.cfg
Labels: branch: master, priority: high, status: enhancement

#1083 Display IDF_CLIENT variables as "Game" in the console usage display.
  config/ui/console.cfg
Labels: branch: master, difficulty: easy, status: enhancement

#1069 add clearconsole & clearchat commands
  config/usage.cfg
  src/engine/console.cpp
  src/engine/main.cpp
Labels: branch: master

#911 Adjust the `maxfps` menu slider
  config/ui/settings.cfg
Labels: branch: master, difficulty: easy, priority: next milestone, status: enhancement

#1097 Put back fx emitters that failed to instantiate
  src/engine/fx.cpp
  src/engine/fx.h
  src/game/game.cpp
  src/game/projs.cpp
Labels: status: bug

#1081 add password prompt for private servers
  config/ui/servers.cfg
Labels: branch: master, difficulty: easy, status: enhancement
