Repository redeclipse/base, pull requests merged in 2020-12, with the labels that each got.

#1110 clang support for msvc-compatible builds
  .gitignore
  src/Makefile
  src/engine/rendermodel.cpp
  src/game/game.cpp
  src/shared/genkey.cpp
  src/shared/tools.h
Labels: status: enhancement

#1114 add playershadow client var
  src/game/game.cpp
Labels: branch: master, difficulty: easy

#1219 skybox & cloudbox spin/yaw/roll/pitch
  src/engine/rendersky.cpp
  src/engine/worldio.cpp
Labels: branch: master, difficulty: easy, status: enhancement
