Repository redeclipse/base, pull requests merged in 2021-12, with the labels that each got.

#1311 Add "Clear" button to vanity selection menu
  config/ui/profile.cfg
Labels: branch: master

#1314 add moveselents command
  src/engine/world.cpp
Labels: branch: master, difficulty: easy

#1315 add dc textures to textures.cfg
  config/map/textures.cfg
Labels: status: enhancement, branch: master

#1308 add ui setting Show Clips
  config/ui/settings.cfg
Labels: status: enhancement, branch: master

#1327 Add an "Always Use High-Quality Models" option to the Graphics menu
  config/ui/settings.cfg
Labels: status: enhancement, branch: master

#1109 fix #315 - add custom colours to routes
  config/usage.cfg
  src/game/entities.cpp
Labels: status: enhancement, branch: master, difficulty: easy

#1329 Add settings for dynamic light and shadow quality
  config/ui/settings.cfg
Labels: status: enhancement, branch: master

#1325 Tweak the default `filetimeformat` to be more readable
  src/engine/server.cpp
Labels: status: enhancement, status: please discuss further, branch: master
